# Generated by Django 3.0 on 2021-12-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_remove_vehicle_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(help_text="Use the following format: 'AA 1111 BP'", max_length=8, unique=True),
        ),
    ]
